version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'; env"
    volumes:
      - .:/railsredditclone
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - app.env

  db:
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - db.env
      
volumes:
  bundle_path:
  postgres-data: